// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"project/internal/http/dao"
	"project/internal/http/service"
)

// Injectors from wire.go:

func NewService() (*service.Service, error) {
	daoDao := dao.New()
	serviceService := service.New(daoDao)
	return serviceService, nil
}

func NewTestService() (*service.Service, error) {
	testdao := dao.NewTestDao()
	serviceService := service.New(testdao)
	return serviceService, nil
}
